Updated to winter 23 information
uwblueprint/website-bp pull request #106
Opened 2023-01-22 06:35 UTC by tshenqka

Updated team to reflect Winter 23 information. Added eslint config change to fix said issue.

2023-01-24 02:43 UTC, aaggarwal10 requested changes

2023-01-24 02:43 UTC, aaggarwal10 commented on constants/members.json
> +      "role": "project lead",
the role for PL's is actually called `Technical Lead`. This should be changed since it is used for sorting and indexing purposes in `utils.ts`.

2023-01-29 04:52 UTC, aaggarwal10 approved these changes
Remember to add a link from github to the notion page and vice versa as described before. Overall though, good job.

2023-01-29 07:27 UTC, skangtan commented
Squash & Merge

2023-01-30 15:20 UTC, tshenqka commented
/trunk merge

2023-01-30 15:20 UTC, merged